"""empty message

Revision ID: 0a4722ee82fe
Revises: c71da72944ed
Create Date: 2024-01-20 15:55:45.773825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4722ee82fe'
down_revision = 'c71da72944ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_item_id_fkey', 'users', ['item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
